# Generated by Django 4.2.10 on 2024-02-16 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djindmin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('a_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djindmin.amodel')),
            ],
        ),
    ]
